name: build

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    name: Various Checks
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Package and its Dependencies
        run: make install
      - name: Lint
        run: make lint
      - name: Check Docstrings
        run: make checkdoc
      - name: Byte Compile
        run: make build
      - name: Run Tests
        run: make test
